name: Clean

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  clean:
    runs-on: ubuntu-latest
    defaults:
      # run:
      #   working-directory: /tmp/gha-work

    steps:
      - uses: actions/checkout@v4
      # - name: Clone repo
      #   uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      #   with:
      #     repository: 'nitro-espresso-integration'
      #     owner: ${{ GITHUB_REPOSITORY_OWNER }}
      - name: move repo
        run: |
          rsync -a ./ /tmp/gha-work/
          cd /tmp/gha-work
          rm -rfv $GITHUB_WORKSPACE
          ln -sv /tmp/gha-work $GITHUB_WORKSPACE
        working-directory: ${{ github.workspace }}

      - name: inspect
        run: |
          echo "PWD" $PWD
          ls -lah

          ls -lah $GITHUB_WORKDIR

      - name: Lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.59.1
          skip-cache: true
          # working-directory: /tmp/gha-work

      # - uses: cargo-bins/cargo-binstall@main

      # - run: |
      #     cargo binstall -y rmz
      #     sudo mv /home/runner/.cargo/bin/rmz /usr/local/bin/rmz

      # - run: |
      #     du -h -d 1 /opt/hostedtoolcache

      # # Make more disk space available on public runner
      # - name: Remove unused software
      #   run: |
      #     echo "Available storage before:"
      #     sudo df -h
      #     echo
      #     sudo rmz -f /usr/share/dotnet
      #     sudo rmz -f /usr/share/swift
      #     sudo rmz -f /usr/share/gradle-*
      #     sudo rmz -f /usr/share/az_*
      #     sudo rmz -f /usr/local/lib/android
      #     sudo rmz -f /usr/local/lib/node_modules
      #     sudo rmz -f /opt/ghc
      #     sudo rmz -f /opt/az
      #     sudo rmz -f /opt/pipx
      #     sudo rmz -f /opt/google
      #     sudo rmz -f /opt/microsoft
      #     sudo rmz -f /opt/hostedtoolcache
      #     echo "Available storage after:"
      #     sudo df -h
      #     echo
